"use client"

import { Geist, Geist_Mono } from "next/font/google"
import LoadingScreen from "@/components/loading"
import { useState, useEffect } from "react"
import { ParallaxProvider } from 'react-scroll-parallax';
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  const [isLoadingComplete, setIsLoadingComplete] = useState(false)

  useEffect(() => {
    const timer = setTimeout(() => setIsLoadingComplete(true), 5500)
    return () => clearTimeout(timer)
  }, [])

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ParallaxProvider>

          {!isLoadingComplete ? <LoadingScreen /> : children}
        </ParallaxProvider>
      </body>
    </html>
  )
}